gramatica = [
    {'PROGRAMA':['BEGIN','SENTENCIAS','END']},
    {'SENTENCIAS':['OPCIONES', 'SENTENCIAS']},
    {'SENTENCIAS':['$']},
    {'OPCIONES':['PEDIRDATOS']},
    {'OPCIONES':['ESCRIBIRDATOS']},
    {'OPCIONES':['DECLARACION']},
    {'OPCIONES':['ASIGNACION']},
    {'ESCRIBIRDATOS':['write','IMPRIMIR','IMPRIMIRR','SIGNO_FINAL']},
    {'PEDIRDATOS':['read','VARIABLE','VARIABLES','SIGNO_FINAL']},
    {'DECLARACION':['TIPO_DATO','VARIABLE','VARIABLES','SIGNO_FINAL']},
    {'ASIGNACION':['VARIABLE','ASIGNAR', 'OPERACIONES','SIGNO_FINAL']},
    {'ASIGNAR':['SIGNO_IGUAL','TIPOASIGNACION']},
    {'TIPOASIGNACION':['OPERACION']},
    {'TIPOASIGNACION':['CADENA']},
    {'TIPOASIGNACION':['CHAR']},
    {'VARIABLES':[',','VARIABLE','VARIABLES']},
    {'VARIABLES':['$']},
    {'VARIABLEE':['num','VARIABLEE']},
    {'VARIABLEE':['letra','VARIABLEE']},
    {'VARIABLEE':['$']},
    #{'VARIABLE':['num','VARIABLEE']},
    {'VARIABLE':['letra','VARIABLEE']},
    {'IMPRIMIRR':[',','IMPRIMIR','IMPRIMIRR']},
    {'IMPRIMIRR':['$']},
    {'IMPRIMIR':['ENTERO','IMPRIMIRR']},
    {'IMPRIMIR':['CADENA','IMPRIMIRR']},
    {'IMPRIMIR':['VARIABLE','IMPRIMIRR']},
    {'IMPRIMIR':['CHAR']},
    {'TIPO_DATO':['int']},
    {'TIPO_DATO':['float']},
    {'TIPO_DATO':['char']},
    {'TIPO_DATO':['string']},
    {'OPERACIONES':['OPERADOR','OPERANDO','OPERACIONES']},
    {'OPERACIONES':['$']},
    #{'OPERACION':['eval','VARIABLE','OPERADOR','VARIABLE']},
    {'OPERANDO':['VARIABLE']},
    {'OPERANDO':['ENTERO']},
    {'OPERACION':['OPERANDO']},
    {'OPERADOR':['*']},
    {'OPERADOR':['/']},
    {'OPERADOR':['+']},
    {'OPERADOR':['-']},
    {'ENTEROS':['num','ENTEROS']},
    {'ENTEROS':['FLOAT']},
    {'FLOAT':['.','ENTERONV']},
    {'ENTEROS':['$']},
    {'ENTERO':['num','ENTEROS']},
    {'ENTERONV':['num','ENTERONV']},
    {'ENTERONV':['$']},
    {'CADENAS':['letra','CADENAS']},
    {'CADENAS':['num','CADENAS']},
    {'CADENAS':['CARACTERES_ESPECIALES','CADENAS']},
    {'CADENAS':['$']},
    {'CADENA':['"','CADENAS','"','CADENAE']},
    {'CADENAE':['+','TIPO_CONCATENACION']},
    {'CADENAE':['$']},
    {'TIPO_CONCATENACION':['CADENA']},
    {'TIPO_CONCATENACION':['VARIABLE']},
    {'CHAR':['\'','ALFANUMERICO','\'']},
    {'ALFANUMERICO':['num']},
    {'ALFANUMERICO':['letra']},
    {'CARACTERES_ESPECIALES':[' ']},
    {'CARACTERES_ESPECIALES':[',']},
    {'CARACTERES_ESPECIALES':['.']},
    {'CARACTERES_ESPECIALES':['-']},
    {'CARACTERES_ESPECIALES':['_']},
    {'CARACTERES_ESPECIALES':['|']},
    {'CARACTERES_ESPECIALES':['!']},
    {'CARACTERES_ESPECIALES':['¡']},
    {'CARACTERES_ESPECIALES':['(']},
    {'CARACTERES_ESPECIALES':[')']},
    {'CARACTERES_ESPECIALES':['@']},
    {'CARACTERES_ESPECIALES':[':']},
    {'num':['0']},
    {'num':['1']},
    {'num':['2']},
    {'num':['3']},
    {'num':['4']},
    {'num':['5']},
    {'num':['6']},
    {'num':['7']},
    {'num':['8']},
    {'num':['9']},
    {'letra':['a']},
    {'letra':['b']},
    {'letra':['c']},
    {'letra':['d']},
    {'letra':['e']},
    {'letra':['f']},
    {'letra':['g']},
    {'letra':['h']},
    {'letra':['i']},
    {'letra':['j']},
    {'letra':['k']},
    {'letra':['l']},
    {'letra':['m']},
    {'letra':['n']},
    {'letra':['o']},
    {'letra':['p']},
    {'letra':['q']},
    {'letra':['r']},
    {'letra':['s']},
    {'letra':['t']},
    {'letra':['u']},
    {'letra':['v']},
    {'letra':['w']},
    {'letra':['x']},
    {'letra':['y']},
    {'letra':['z']},
    {'letra':['A']},
    {'letra':['B']},
    {'letra':['C']},
    {'letra':['D']},
    {'letra':['E']},
    {'letra':['F']},
    {'letra':['G']},
    {'letra':['H']},
    {'letra':['I']},
    {'letra':['J']},
    {'letra':['K']},
    {'letra':['L']},
    {'letra':['M']},
    {'letra':['N']},
    {'letra':['O']},
    {'letra':['P']},
    {'letra':['Q']},
    {'letra':['R']},
    {'letra':['S']},
    {'letra':['T']},
    {'letra':['U']},
    {'letra':['V']},
    {'letra':['W']},
    {'letra':['X']},
    {'letra':['Y']},
    {'letra':['Z']},
    {'SIGNO_IGUAL':['=']},
    {'SIGNO_FINAL':[';']}
]



lista_filtrar = ["PROGRAMA", "SENTENCIAS"]

def reemplazar_claves(gramatica, claves_reemplazo):
    reemplazado = []
    claves = list(map(lambda x: x[0], claves_reemplazo))
    for objeto in gramatica:
        nombre = list(objeto.keys())[0]
        if(nombre in claves):
            reemplazado.append({claves_reemplazo[claves.index(nombre)][1]:objeto[nombre]})
        else:
            reemplazado.append(objeto)
    return reemplazado
def filtrar(gramatica,claves):
    filtrado = []
    for objeto in gramatica:
        nombre = list(objeto.keys())[0]
        if(nombre not in claves):filtrado.append(objeto)
    return filtrado
gramatica_individual = filtrar(gramatica, lista_filtrar)


reemplazos = [("OPCIONES","PROGRAMA")]
gramatica_individual = reemplazar_claves(gramatica_individual, reemplazos)
#print(gramatica_individual)

